part_1:
  id: 8974112740
  number: 625
  shagiri: 7
  kind: small_part
  color: black_silver
  mass: 0.020000
  aligned: true
  cluttered: false
  entanglement: false
  gripper: suction
  grippable: false
  robot: false
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: true
  name: ワイヤレスドアコンレシーバー
part_2:
  id: 8974012480
  number: 71
  shagiri: 7
  kind: small_part
  color: black_silver
  mass: 0.020000
  aligned: true
  cluttered: false
  entanglement: false
  gripper: suction
  grippable: false
  robot: false
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: true
  name: ドアコンレシーバー
part_3:
  id: 8974012380
  number: 601
  shagiri: 7
  kind: small_part
  color: black_silver
  mass: 0.020000
  aligned: true
  cluttered: false
  entanglement: false
  gripper: suction
  grippable: false
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: true
  name: ドアコンレシーバー
part_4:
  id: 6462133030
  number: 553
  shagiri: 0
  kind: small_BKT
  color: silver
  mass: 0.025000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: STRIKER LUGGAGE_COMPARTMENT
part_5:
  id: 8539048060
  number: 181
  shagiri: 0
  kind: short_hose
  color: black
  mass: 0.020000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: two_finger
  grippable: false
  robot: false
  human: true
  either: false
  box: TP331
  box_cover: false
  wrapped: true
  insole: false
  separation: false
  name: RRウォッシャーノズル
part_8:
  id: 6943048030
  number: 662
  shagiri: 0
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: STRIKER_ASSY BACKDOOR_LOCK
part_9:
  id: 8974112730
  number: 166
  shagiri: 7
  kind: small_part
  color: black_silver
  mass: 0.020000
  aligned: true
  cluttered: false
  entanglement: false
  gripper: suction
  grippable: false
  robot: false
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: true
  name: ワイヤレスドアコンレシーバー
part_18:
  id: 6894612060
  number: 78
  shagiri: 10
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET BACKDOOR_DAMPER_STAY
part_19:
  id: 6894512090
  number: 57
  shagiri: 10
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: false
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET BACKDOOR_DAMPER_STAY
part_20:
  id: 5833212110
  number: 117
  shagiri: 11
  kind: small_BKT
  color: black
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: true
  separation: false
  name: BRACKET LUGGAGE_COMPARTMENT
part_21:
  id: 5833112120
  number: 94
  shagiri: 11
  kind: small_BKT
  color: black
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: true
  separation: false
  name: BRACKET LUGGAGE_COMPARTMENT
part_22:
  id: 6165448050
  number: 830
  shagiri: 0
  kind: small_BKT
  color: silver
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: true
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET DECKSIDE_TRIM LH
part_23:
  id: 6165348050
  number: 818
  shagiri: 0
  kind: small_BKT
  color: silver
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: true
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET DECKSIDE_TRIM RH
part_26:
  id: 5201512480
  number: 70
  shagiri: 0
  kind: middle_sized_BKT
  color: black
  mass: 0.500000
  aligned: true
  cluttered: false
  entanglement: false
  gripper: two_finger
  grippable: false
  robot: false
  human: true
  either: false
  box: TP332
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: ARMSUB-ASSY RR_BUMPER RH
part_38:
  id: 6737248070
  number: 97
  shagiri: 0
  kind: small_BKT
  color: black_silver
  mass: 0.300000
  aligned: false
  cluttered: true
  entanglement: true
  gripper: magnet
  grippable: true
  robot: true
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: WEIGHT BACKDOOR
part_41:
  id: 6894648050
  number: 275
  shagiri: 2
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET BACKDOOR_DAMPERSTAY
part_42:
  id: 6894548110
  number: 111
  shagiri: 2
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET BACKDOOR_DAMPERSTAY
part_43:
  id: 6894648070
  number: 49
  shagiri: 2
  kind: small_BKT
  color: black
  mass: 0.100000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: 新聞紙
  separation: false
  name: BRACKET BACKDOOR_DAMPERSTAY
part_44:
  id: 6894548070
  number: 13
  shagiri: 2
  kind: small_BKT
  color: black
  mass: 0.050000
  aligned: false
  cluttered: true
  entanglement: false
  gripper: magnet
  grippable: true
  robot: false
  either: false
  box: TP331
  box_cover: false
  wrapped: false
  insole: false
  separation: false
  name: BRACKET BACKDOOR_DAMPERSTAY
