# Publish all joint states ----------------------------------
joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 50

scaled_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    arm_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
    arm_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
    arm_elbow_joint: {trajectory: 0.2, goal: 0.1}
    arm_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
    arm_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
    arm_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 500
  action_monitor_rate: 20

gripper_controller:
  type: position_controllers/GripperActionController
  joint: gripper_finger_joint
  goal_tolerance: 0.01
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.2
  gains:
    gripper_finger_joint: {p: 200, d: 1, i: 5, i_clamp: 1}
