<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="mybox"
	       params="name size_x size_y size_z parent *origin">
    <!-- This creates a box with the origin in the bottom corner, fixed to the world link. -->

    <xacro:property name="rgba"	value="0.7 0.7 0.7 1"/>
    <xacro:property name="color_name" value="Grey"/>

    <link name="${name}">
      <visual>
        <origin xyz="${size_x/2} ${size_y/2} ${size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
          <material name="${color_name}">
          <color rgba="${rgba}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${size_x/2} ${size_y/2} ${size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>

      <!-- This is required for Gazebo. -->
      <inertial>
        <mass value="1.0"/>
        <!-- <origin xyz="${size_x/2} ${size_y} ${size_z/2}" rpy="0 0 0"/> -->
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>
    <gazebo reference="${name}">
      <material>Gazebo/${color_name}</material>
    </gazebo>

    <joint name="${name}" type="fixed">
      <parent link="${parent}"/>
      <child  link="${name}"/>
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>

</robot>
