<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="nedo3_demo">

  <xacro:arg name="kinematics_parameters_file"
	     default="$(find ur_description
		      )/config/ur5e/default_kinematics.yaml"/>

  <xacro:property name="lane_separation"	value="2.000"/>
  <xacro:property name="lane_width"		value="0.87"/>
  <xacro:property name="workspace_length"	value="${lane_separation
						       + lane_width}"/>
  <xacro:property name="rack_width"		value="0.85"/>
  <xacro:property name="rack_separation"	value="0.04"/>
  <xacro:property name="rack_t_setback"		value="-0.050"/>
  <xacro:property name="rack_t_elevation"	value="0.595"/>

  <!-- UR5 physical installation (Tsukuba)-->
  <xacro:property name="table_x" value="4.0"/>
  <xacro:property name="table_y" value="-2.0"/>
  <xacro:property name="table_w" value="0.3"/>
  <xacro:property name="table_l" value="0.3"/>
  <xacro:property name="table_h" value="0.7"/>

  <!-- Root frame -->
  <link name="world"/>

  <!-- Main workspace -->
  <link name="ground"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="-4 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Floor -->
  <xacro:property name="floor_width"	value="12.000"/>
  <xacro:property name="floor_length"	value="6.000"/>
  <xacro:include filename="$(find nedo3_description
			   )/urdf/floor.urdf.xacro"/>
  <xacro:floor prefix="demo_" parent="world" width="${floor_width}"
  	       length="${floor_length}" thickness="0">
    <origin xyz="0 0 -0.001" rpy="0 0 0"/>
  </xacro:floor>

  <!-- rack_b0 -->
  <xacro:include filename="$(find nedo3_description
			   )/urdf/rack_b.urdf.xacro"/>
  <xacro:rack_b name="rack_b0" parent="ground">
    <origin xyz="1.5 ${workspace_length/2} 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t0 -->
  <xacro:include filename="$(find nedo3_description
			   )/urdf/rack_t.urdf.xacro"/>
  <xacro:rack_t name="rack_t0" parent="rack_b0">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b1 -->
  <xacro:rack_b name="rack_b1" parent="rack_b0">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t1 -->
  <xacro:rack_t name="rack_t1" parent="rack_b1">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b2 -->
  <xacro:rack_b name="rack_b2" parent="rack_b1">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t2 -->
  <xacro:rack_t name="rack_t2" parent="rack_b2">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b3 -->
  <xacro:rack_b name="rack_b3" parent="rack_b2">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t3 -->
  <xacro:rack_t name="rack_t3" parent="rack_b3">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b4 -->
  <xacro:rack_b name="rack_b4" parent="rack_b3">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t4 -->
  <xacro:rack_t name="rack_t4" parent="rack_b4">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b5 -->
  <xacro:rack_b name="rack_b5" parent="ground">
    <origin xyz="${1.5 + rack_width} ${-workspace_length/2} 0"
	    rpy="0 0 ${pi}"/>
  </xacro:rack_b>

  <!-- rack_t5 -->
  <xacro:rack_t name="rack_t5" parent="rack_b5">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- Put boxes on racks -->
  <xacro:property name="rack_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/rack_props.yaml')}"/>
  <xacro:property name="part_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/part_props.yaml')}"/>
  <xacro:property name="box_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/box_props.yaml')}"/>
  <xacro:include filename="$(find nedo3_description
			   )/urdf/put_boxes_on_racks.urdf.xacro"/>
  <xacro:put_boxes_on_racks rack_props="${rack_props}"
			    part_props="${part_props}"
			    box_props="${box_props}"/>

  <!-- Table for mounting UR5e -->
  <xacro:include filename="$(find nedo3_description)/urdf/table.urdf.xacro"/>
  <xacro:table prefix="arm_"
	       width="${table_w}" length="${table_l}" height="${table_h}"
	       parent="ground">
    <origin xyz="${table_x} ${table_y} 0" rpy="0 0 0"/>
  </xacro:table>

  <!-- Spawn UR5E arm -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="arm_"
      joint_limits_parameters_file="$(find ur_description
				    )/config/ur5e/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
				)/config/ur5e/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
			      )/config/ur5e/visual_parameters.yaml"
      kinematics_parameters_file="$(arg kinematics_parameters_file)"
      transmission_hw_interface="hardware_interface/PositionJointInterface"/>
  <joint name="arm_base_joint" type="fixed">
    <origin xyz="${table_w/2} ${table_l/2} 0" rpy="0 0 0"/>
    <parent link="arm_table_top" />
    <child link="arm_base_link"/>
  </joint>

  <!-- Spawn and attach coupling -->
  <xacro:include filename="$(find aist_robotiq
  			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="gripper_coupling_" parent="arm_flange">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_robotiq
  			   )/urdf/robotiq_85_gripper.urdf.xacro"/>
  <xacro:robotiq_85_gripper prefix="gripper_"
			     parent="gripper_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper>
</robot>
