<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="showcase">

  <xacro:property name="lane_separation"	value="2.000"/>
  <xacro:property name="lane_width"		value="0.87"/>
  <xacro:property name="workspace_length"	value="${lane_separation
						       + lane_width}"/>
  <xacro:property name="rack_width"		value="0.85"/>
  <xacro:property name="rack_separation"	value="0.04"/>
  <xacro:property name="rack_t_setback"		value="-0.050"/>
  <xacro:property name="rack_t_elevation"	value="0.595"/>

  <!-- Root frame -->
  <link name="world"/>

  <!-- Main workspace -->
  <link name="ground"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="-4 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Floor -->
  <xacro:property name="floor_width"	value="12.000"/>
  <xacro:property name="floor_length"	value="6.000"/>
  <xacro:include filename="$(find nedo3_description
			   )/urdf/floor.urdf.xacro"/>
  <xacro:floor prefix="demo_" parent="world" width="${floor_width}"
  	       length="${floor_length}" thickness="0">
    <origin xyz="0 0 -0.001" rpy="0 0 0"/>
  </xacro:floor>

  <!-- rack_b0 -->
  <xacro:include filename="$(find nedo3_description
			   )/urdf/rack_b.urdf.xacro"/>
  <xacro:rack_b name="rack_b0" parent="ground">
    <origin xyz="1.5 ${workspace_length/2} 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t0 -->
  <xacro:include filename="$(find nedo3_description
			   )/urdf/rack_t.urdf.xacro"/>
  <xacro:rack_t name="rack_t0" parent="rack_b0">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b1 -->
  <xacro:rack_b name="rack_b1" parent="rack_b0">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t1 -->
  <xacro:rack_t name="rack_t1" parent="rack_b1">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b2 -->
  <xacro:rack_b name="rack_b2" parent="rack_b1">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t2 -->
  <xacro:rack_t name="rack_t2" parent="rack_b2">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b3 -->
  <xacro:rack_b name="rack_b3" parent="rack_b2">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t3 -->
  <xacro:rack_t name="rack_t3" parent="rack_b3">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b4 -->
  <xacro:rack_b name="rack_b4" parent="rack_b3">
    <origin xyz="${rack_width + rack_separation} 0 0" rpy="0 0 0"/>
  </xacro:rack_b>

  <!-- rack_t4 -->
  <xacro:rack_t name="rack_t4" parent="rack_b4">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- rack_b5 -->
  <xacro:rack_b name="rack_b5" parent="ground">
    <origin xyz="${1.5 + rack_width} ${-workspace_length/2} 0"
	    rpy="0 0 ${pi}"/>
  </xacro:rack_b>

  <!-- rack_t5 -->
  <xacro:rack_t name="rack_t5" parent="rack_b5">
    <origin xyz="0 ${rack_t_setback} ${rack_t_elevation}" rpy="0 0 0"/>
  </xacro:rack_t>

  <!-- Put boxes on shooters -->
  <xacro:include filename="$(find nedo3_description
			   )/urdf/put_boxes_on_racks.urdf.xacro"/>

  <xacro:property name="rack_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/rack_props.yaml')}"/>
  <xacro:property name="part_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/part_props.yaml')}"/>
  <xacro:property name="box_props"
		  value="${xacro.load_yaml('$(find nedo3_description
			 )/config/box_props.yaml')}"/>
  <xacro:put_boxes_on_racks rack_props="${rack_props}"
			    part_props="${part_props}"
			    box_props="${box_props}"/>

</robot>
